name: Tests

on: [push]

env:
  WEBFLOW_API_KEY: "bogus"
  ALGOLIA_APP_ID: BP6X6YAZSL
  ALGOLIA_API_KEY: "bogus"
  CURRENT_SITE: ottawa
  SENTRY_DSN: https://bogus@bogus.ingest.sentry.io/123

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  deploy-mirrors:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v2
      - name: Set up mirrors
        run: bin/ci-mirror-setup
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: airhorns/together-apart-outaouais
          github_token: ${{ secrets.INPUT_GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: airhorns/together-apart-durham
          github_token: ${{ secrets.INPUT_GITHUB_TOKEN }}
      - name: Deploy to mirrors
        run: bin/deploy-mirrors
